default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  host: localhost
  port: 3306

development:
  <<: *default
  database: friends_app_development

test:
  <<: *default
  database: friends_app_test

production:
  primary:
    <<: *default
    database: friends_app_production
    username: <%= ENV["MYSQL_USER"] || "root" %>
    password: <%= ENV["MYSQL_PASSWORD"] %>
    host: <%= ENV["MYSQL_HOST"] || "localhost" %>

  cache:
    <<: *default
    database: friends_app_cache
    migrations_paths: db/cache_migrate

  queue:
    <<: *default
    database: friends_app_queue
    migrations_paths: db/queue_migrate

  cable:
    <<: *default
    database: friends_app_cable
    migrations_paths: db/cable_migrate
